import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
v = pd.read_csv('diabetes.csv')
x = v.drop('Outcome', axis=1)
y = v['Outcome']
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)
pca = PCA()
pca.fit(x_scaled)
print("Explained variance ratio:")
for i, var in enumerate(pca.explained_variance_ratio_):
    print(f"Principal Component {i+1}: {var:.4f} {var*100:.2f}%")
cumulative_variance = np.cumsum(pca.explained_variance_ratio_)
print("\nCumulative explained variance:", cumulative_variance)
plt.figure(figsize=(8, 5))
plt.bar(range(1, 9), pca.explained_variance_ratio_)
plt.step(range(1, 9), cumulative_variance, where='mid', color='red', label='Cumulative Variance')
plt.xlabel('Principal Components')
plt.ylabel('Explained Variance Ratio')
plt.title('PCA Explained Variance')
plt.legend()
plt.show()
pca_final = PCA(n_components=0.95)
x_pca = pca_final.fit_transform(x_scaled)
print("\nShape of original data:", x_scaled.shape)
print(f"reduced shape: {x_pca.shape}")
print(f"components kept: {pca_final.n_components_}")
pca2 = PCA(n_components=2)
x_pca2 = pca2.fit_transform(x_scaled)
plt.figure(figsize=(8, 6))
plt.scatter(x_pca2[y==0, 0], x_pca2[y==0, 1], color='blue', label='No Diabetes', alpha=0.5)
plt.scatter(x_pca2[y==1, 0], x_pca2[y==1, 1], color='orange', label='Diabetes', alpha=0.5)
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA Scatter Plot')
plt.legend()
plt.show()